### ISSUE TITLE
next error at stop command while unloading level

### ISSUE THREAD

**Issue by SleepSpace9** [iTXTech/Genisys#92]
Sorry, I got one more error while unloading another level:
...
[14:55:21] [Server thread/INFO]: Unloading level "Survival"
[14:55:21] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\level\Position::setLevel() must be an instance of pocketmine\level\Level, null given, called in /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/entity/Entity.php on line 239" (EXCEPTION) in "/github-genisys/src/pocketmine/level/Position" at line 64

Fatal error: Uncaught Error: Call to a member function getName() on null in /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/level/Level.php:2896
Stack trace:
#0 /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/level/Position.php(121): pocketmine\level\Level->getName()
#1 /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/PocketMine.php(369): pocketmine\level\Position->__toString()
#2 /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/utils/MainLogger.php(146): pocketmine\getTrace(1, Array)
#3 /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/Server.php(2490): pocketmine\utils\MainLogger->logException(Object(TypeError), Array)
#4 /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/Server.php(1987): pocketmine\Server->exceptionHandler(Object(TypeError))
#5 /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/PocketMine.php(463): pocketmine\Server->__construct(Object(pocketmine\CompatibleClassLoader), Object(pocketmine\utils\MainLogger), '/home/rene/Pock...',  in /home/rene/PocketMine-MP-php7/github-genisys/src/pocketmine/level/Level.php on line 2896

**Comment by SleepSpace9** [comment]
The error doesn't occur with the latest version, so I close this issue.
